version: "2.2"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: es01
    restart: always
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${BASE_VOLUME_DIR}/elastic/data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic-net

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: es02
    restart: always
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es01"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${BASE_VOLUME_DIR}/elastic/data02:/usr/share/elasticsearch/data
    networks:
      - elastic-net

  kib01:
    image: docker.elastic.co/kibana/kibana:6.6.1
    container_name: kib01
    restart: always
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200"]'
    networks:
      - elastic-net

networks:
  elastic-net:
    driver: bridge
