version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80/tcp"
    environment:
      TZ: "Asia/Kuala_Lumpur"
      WEBPASSWORD: ${PIHOLE_WEB_PASSWORD}
    volumes:
      - "${BASE_VOLUME_DIR}/pihole/etc/pihole:/etc/pihole"
      - "${BASE_VOLUME_DIR}/pihole/etc/dnsmasq.d:/etc/dnsmasq.d"
    restart: always
