services:
  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    container_name: ollama
    pull_policy: always
    ports:
      - 11434:11434
    tty: true
    restart: always
    volumes:
      - "${BASE_VOLUME_DIR}/ollama:/root/.ollama"

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    pull_policy: always
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-8080}:8080
    environment:
      - 'DATABASE_URL=${OPEN_WEBUI_DATABASE_URL}'
      - 'ENABLE_OLLAMA_API=${OPEN_WEBUI_ENABLE_OLLAMA_API-True}'
      - 'OLLAMA_BASE_URL=${OPEN_WEBUI_OLLAMA_BASE_URL-http://ollama:11434}'
      - 'WEBUI_SECRET_KEY=${OPEN_WEBUI_SECRET_KEY}'
      - 'ENABLE_IMAGE_GENERATION=${OPEN_WEBUI_ENABLE_IMAGE_GENERATION-False}'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    volumes:
      - "${BASE_VOLUME_DIR}/open-webui:/app/backend/data"
