version: "3.7"

services:
  gitlab-runner:
    image: feedsbrain/buildmystack:0.2.9
    container_name: gitlab-runner
    restart: always
    command: bash -lc "sudo gitlab-runner start && tail -f /dev/null"
    volumes:
      - ${BASE_VOLUME_DIR}/gitlab-runner/config:/etc/gitlab-runner
      - ${BASE_VOLUME_DIR}/gitlab-runner/runner:/home/gitlab-runner
    environment:
      - TZ=Asia/Kuala_Lumpur

  gitlab-docker:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-docker
    restart: always
    privileged: true
    volumes:
      - ${BASE_VOLUME_DIR}/gitlab-docker/config:/etc/gitlab-runner
      - ${BASE_VOLUME_DIR}/gitlab-docker/runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Kuala_Lumpur
