version: "3.1"

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    volumes:
      - ${BASE_VOLUME_DIR}/minio:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
