version: "3.1"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - ${BASE_VOLUME_DIR}/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
